### PR TITLE
Kpt extend format + bugfix in conversion sdor from old ERA5

### PR DESCRIPTION
**Pull request by sjboeing**
@leifdenby: this branch adds the seconds and date to the KPT format. It also solves an issue with the old units in ERA5: you will see this on quickly, it has to do with a change in units which we apply before we check the units.

### CODE REVIEW

**Comment by sjboeing** [comment]
Not sure whether to bring this all into 0.1.0, or only the smaller bug fix. Let me know what is your preference.

**Comment by leifdenby** [comment]
I think we should leave this for the next release. We can always make `v0.1.1`. I don't quite understand the changes you made (and reverted) for the `sdor` variable. So let's talk about this

**Comment by sjboeing** [comment]
Hi @leifdenby: thanks for having a look. Without the bugfix in line 372, it is not possible to produce KPT files, so I would like to change this one line for 0.1.0 if possible. The problem results from already changing the units via a dictionary (from "1" to "0-1", which I think is still required for some other variables) before changing them again.

Just ignore the reverted change (which is an alternative approach to fixing the issue). 

The second (of the day) and date (as a number) are useful for the UM SCM, these fields are usually included in KPT files. With our date format they are duplicate information, but it makes it easier to read this information into fortran code. This change is less crucial, though I would be keen to include it quite soon.

**Comment by leifdenby** [comment]
> Hi @leifdenby: thanks for having a look. Without the bugfix in line 372, it is not possible to produce KPT files, so I would like to change this one line for 0.1.0 if possible. The problem results from already changing the units via a dictionary (from "1" to "0-1", which I think is still required for some other variables) before changing them again.
> 
> Just ignore the reverted change (which is an alternative approach to fixing the issue).
> 
> The second (of the day) and date (as a number) are useful for the UM SCM, these fields are usually included in KPT files. With our date format they are duplicate information, but it makes it easier to read this information into fortran code. This change is less crucial, though I would be keen to include it quite soon.

Ok, I'm just wary of changing more than one thing in a single pull-request, since this is both fixing a bug and making an addition. I'll write the changelog to indicate both changes and merge this before tagging and publishing `v0.1.1`

**Comment by sjboeing** [comment]
Thanks @leifdenby: sorry to bring this in last minute.

**Comment by leifdenby** [comment]
no problem :)

**Pull request merged**
