### PR TITLE
final readthrough of README before v0.1.0

### PR DESCRIPTION
**Pull request by leifdenby**

### CODE REVIEW

**Comment by leifdenby** [comment]
Right, this is ready for review again @sjboeing when you have a chance. Might be easiest to view the full README on the branch: https://github.com/leifdenby/lagtraj/tree/readme-readthrough-before-v0.1.0

**Review by sjboeing — COMMENTED** [review]
Thanks, @leifdenby: this looks good to me. Did you try running all commands? If so, I am happy for you to merge. If not, I could try this as well.

**Comment by sjboeing** [comment]
P.S: With that, I think we are ready to tag version 0.1.0.

**Comment by leifdenby** [comment]
> Thanks, @leifdenby: this looks good to me. Did you try running all commands? If so, I am happy for you to merge. If not, I could try this as well.

All the commands in the README are automatically run as of https://github.com/EUREC4A-UK/lagtraj/pull/143 :) you can see the code here: https://github.com/EUREC4A-UK/lagtraj/blob/master/tests/test_cli.py#L130

**Pull request merged**
