### PR TITLE
add zenodo doi badge and citation file

### PR DESCRIPTION
**Pull request by leifdenby**
I've set up the zenodo integration for our github organisation which ensures the future releases on github area automatically uploaded to zenodo and given a DOI. I've also made sure that our existing releases on github have been pushed to zenodo (using https://github.com/imcf/zenodo-doi-for-existing-release). I've added a zenodo doi badge to the README and created a  `CITATION.cff` file as zenodo recommend you do (https://citation-file-format.github.io/).

Could you have a look @sjboeing and let me know if this looks ok to you?

### CODE REVIEW

**Comment by sjboeing** [comment]
The idea of automatically creating a DOI sounds good. I was wondering whether these new files need to be updated manually (apologies, the zenodo-thing is a bit new to me).

**Comment by leifdenby** [comment]
> I was wondering whether these new files need to be updated manually (apologies, the zenodo-thing is a bit new to me).

It is all automatic :) Every release created on github is automatically uploaded to zenodo and given a doi. And the link in the README will always point to the most recent release

**Comment by sjboeing** [comment]
Happy for you to merge this @leifdenby.

**Review by sjboeing — APPROVED** [review]

**Comment by leifdenby** [comment]
> Happy for you to merge this @leifdenby.

Great, thanks! I've just updated the changelog and once the tests pass I will merge this in.

**Pull request merged**
