### PR TITLE
Change to surface temperature: use skin temperature instead of soil layer 1 plus 1K as previously.

### PR DESCRIPTION
**Pull request by sjboeing**
@leifdenby: these are the changes I would like to pull, but need to ensure tests pass.

### CODE REVIEW

**Comment by leifdenby** [comment]
The tests are failing because the `skt_mean` variable is missing. Is that a new variable from ERA5 that we didn't previously download? In that case I will need to update the test-data (again)

**Comment by leifdenby** [comment]
> The tests are failing because the `skt_mean` variable is missing. Is that a new variable from ERA5 that we didn't previously download? In that case I will need to update the test-data (again)

I've just answered my question by looking at the changes this pull-request makes the ERA5 download routines: Yes, this is an additional variable we didn't download before.

I'll create some new test-data, package it and upload to JASMIN

**Comment by leifdenby** [comment]
I've created and uploaded new test-data to JASMIN, rerunning CI tests

**Comment by leifdenby** [comment]
@sjboeing there's a new issue now, something about the unit conversion for `sdor`: https://github.com/EUREC4A-UK/lagtraj/runs/8202717852?check_suite_focus=true#step:6:668 - maybe you could have a look at this?

**Comment by sjboeing** [comment]
@leifdenby Mmm, that's confusing. Wondering if the units in ERA5 have been updated. The table here (https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation) shows no units, whereas the details show units as "m" (https://apps.ecmwf.int/codes/grib/param-db?id=160). I would suggest to change the units in lagtraj/forcings/conversion/targets/kpt.py to "m" for "forward compatibility". The drawback is that it means data that was downloaded previously may no longer be compatible.

**Comment by sjboeing** [comment]
Just seeing @xychen-ocn found the same!

**Comment by leifdenby** [comment]
> I would suggest to change the units in lagtraj/forcings/conversion/targets/kpt.py to "m" for "forward compatibility". The drawback is that it means data that was downloaded previously may no longer be compatible.

How about we allow for both with and without units for `sdor`?

**Comment by leifdenby** [comment]
Just looking at the `history` attribute in the of on the of the files in the `eurec4a_circle` domain dataset (for what we currently have in the test-dataset on JASMIN):

```
:history = "2022-09-06 08:28:26 GMT by grib_to_netcdf-2.25.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf.bin -S param -o /cache/data9/adaptor.mars.external-1662452668.323309-24594-18-2d977cd3-b05c-489f-80e3-f29a7c2bd85e.nc /cache/tmp/2d977cd3-b05c-489f-80e3-f29a7c2bd85e-adaptor.mars.external-1662451332.0694354-24594-30-tmp.grib" ;
```
Compared to an older file:

```
history = "2020-07-07 12:33:06 GMT by grib_to_netcdf-2.16.0: /opt/ecmwf/eccodes/bin/grib_to_netcdf -S param -o /cache/data4/adaptor.mars.external-1594120733.0836775-21229-17-35fa5f55-06c1-431c-b0ac-6b2be9dc22b1.nc /cache/tmp/35fa5f55-06c1-431c-b0ac-6b2be9dc22b1-adaptor.mars.external-1594120733.084247-21229-6-tmp.grib" ;
```


It looks like the version of `grib_to_netcdf` has changed?  I had a quick look in the eccodes repo (https://github.com/ecmwf/eccodes), but I could see an obvious change between the two versions, but I'm sure it would be there if I dig a bit deeper...

**Comment by leifdenby** [comment]
Yes, here it is (from https://confluence.ecmwf.int/display/ECC/History+of+Changes):

```
Version 2.22.0 (May 2021)

New Features/Improvements

    [[ECC-1233](https://jira.ecmwf.int/browse/ECC-1233)] - grib_filter: Allow printing of 'byte' keys like bitmap and section paddings
    [[ECC-1227](https://jira.ecmwf.int/browse/ECC-1227)] - GRIB2: Add new parameter "tropopause pressure"
    [[ECC-1231](https://jira.ecmwf.int/browse/ECC-1231)] - Python2 bindings: Remove the experimental high-level interface
    [[ECC-1232](https://jira.ecmwf.int/browse/ECC-1232)] - GRIB: Add units to orography fields
    [[ECC-1235](https://jira.ecmwf.int/browse/ECC-1235)] - Fortran examples: Show how to convert an error code into a string
    [[ECC-1236](https://jira.ecmwf.int/browse/ECC-1236)] - MARS Streams: Support next ENS-Extended range configuration
    [[ECC-1239](https://jira.ecmwf.int/browse/ECC-1239)] - grib_get_data: Polar Stereographic: Better error message if earth is oblate
```

**Comment by leifdenby** [comment]
So to do this properly we'd pare the `grib_to_netcdf` version out of the history attribute and check what the version is and allow the units to be missing.

I would suggest that we simply set the units to what they should be (i.e. `m` for the standard deviation of orography) if they aren't set. In the line above where this is done I would add a comment referencing that older ERA5 files (produced with `grib_to_netcdf(eccodes)<=2.22.0 (May 2021)` was missing the units for `sdor` so we set them explicitly here

**Comment by sjboeing** [comment]
Thanks, Leif. I would like to retain the checks in general, but possibly we can accept both options [-/m] for sdor and overwrite by [m]. This would mean some variable-specific code, hopefully this can be limited to a few lines in one place.

More generally, I am wondering how we can make the test framework easier to maintain (for example, if we want to download another variable).

**Comment by leifdenby** [comment]
> accept both options [-/m] for sdor and overwrite by [m]. This would mean some variable-specific code, hopefully this can be limited to a few lines in one place.

Right, I'll do this!

**Comment by sjboeing** [comment]
@leifdenby: let me know if I can help with this. Maybe I can come up with a temporary solution, which we can then improve on.

**Comment by sjboeing** [comment]
Thanks @leifdenby. This looks like a good approach, though it still seems to crash at the moment. I will get back to this.

**Comment by sjboeing** [comment]
@leifdenby: it may be a matter of changing the units on line 191 of kpt.py to "m"

**Comment by leifdenby** [comment]
It was that, but also I was being optimistic and didn't run the tests locally :) I've done that now and fixed a few other typos

**Comment by sjboeing** [comment]
Thanks @leifdenby , I am happy to merge this now if that is OK for you too.

**Comment by leifdenby** [comment]
> Thanks @leifdenby , I am happy to merge this now if that is OK for you too.

Yes, will you write in the commit message what the change is to how the surface temperature is calculated? It isn't quite clear to me from the commit messages, e.g. "Work in progress on surf temp changes "

**Comment by leifdenby** [comment]
Actually. The changes to handle the unit change to "sdor" should really be a separate pull-request, since it doesn't have anything to do with the changes you opened this pull-request for, right? If that's right I'd like to make a separate pull-request first.

**Comment by sjboeing** [comment]
@leifdenby: Sure, sounds good to do it in that order.

**Comment by leifdenby** [comment]
> @leifdenby: Sure, sounds good to do it in that order.

Ok, good. I'll make that pull-request

**Comment by sjboeing** [comment]
@leifdenby: just let me know once it is merged, and I can then get back to this one.

**Comment by leifdenby** [comment]
All done ! :partying_face: 

I'll get `v0.1.0` released on pypi :)

**Pull request merged**
