### PR TITLE
Timings on master

### PR DESCRIPTION
**Pull request by sjboeing**
Hi Leif,

Here is a pull request to ensure the first and last time step data are included in lagtraj, also including your work. Will still need to see it passes all the relevant tests.

Steef

### CODE REVIEW

**Comment by sjboeing** [comment]
@leifdenby: do you have any idea where in CI this gets stuck?

**Comment by sjboeing** [comment]
Working to test this on my local machine

**Comment by leifdenby** [comment]
I'll complete https://github.com/EUREC4A-UK/lagtraj/pull/159 first and fix the issue there, get that pull-request merged. Then I'll look at this

**Comment by leifdenby** [comment]
> @leifdenby: do you have any idea where in CI this gets stuck?

Yes, this is an issue with python3.6 and the `setuptools_scm` package that I had set up for the package versioning of lagtraj. I've removed the use of `setuptools_scm` in https://github.com/EUREC4A-UK/lagtraj/pull/165 though because it was too much effort to get it to work and too brittle with python3.6

**Comment by leifdenby** [comment]
I've just been reading through this and I think I get it now :) With my work in https://github.com/EUREC4A-UK/lagtraj/pull/159 I was intending to both write a test to *demonstrate the issue* and also *fix the issue*. I was going to do both, I just wanted to make sure that you were happy with how I'd written the test and that I'd understood the issue correctly. I've finished fixing the issue now too.

**Pull request closed without merging**
