### PR TITLE
ERA5 forcings

### PR DESCRIPTION
**Pull request by leifdenby**
This pull-request represents work to refactor the forcing profile calculations by @sjboeing in https://github.com/sjboeing/lagtraj/blob/231732df9eba08208d91c2cfa4bbf39454e3454a/lagtraj/utils/era5_heights_pressures.py to work with the data-loading, tests etc and split that code into individual modules.

### CODE REVIEW

**Comment by leifdenby** [comment]
@sjboeing this is ready for your review now 😄 

As you can see there is a minor issue with the forcing at the "origin" time in the trajectory. I think this is because of how I pick the `u_traj` and `v_traj` for that point, I think I'm doing that incorrectly, but I'm not sure what to do and couldn't quite work it out from your code. Maybe we can talk about that? 

eurec4a_20191209_12_lag

Producing forcing takes about 48s, that's for a total of 25 timesteps. I've added the `eurec4a_20191209_12_lag` input definition for the forcing to the repository so you can give it a go on the same setup.

```bash
$> pyinstrument -m lagtraj.forcings.create eurec4a_20191209_12_lag
...
  _     ._   __/__   _ _  _  _ _/_   Recorded: 19:06:43  Samples:  40899
 /_//_/// /_\ / //_// / //_'/ //     Duration: 50.246    CPU time: 47.878
/   _/                      v3.1.3

Program: lagtraj.forcings.create eurec4a_20191209_12_lag

50.246 <module>  <string>:1
└─ 50.246 run_module  runpy.py:195
      [4 frames hidden]  runpy
         47.271 _run_code  runpy.py:62
         └─ 47.271 <module>  lagtraj/forcings/create.py:1
            └─ 47.246 main  lagtraj/forcings/create.py:105
               └─ 46.691 make_forcing  lagtraj/forcings/create.py:54
                  └─ 46.387 calculate_timestep  lagtraj/forcings/profile_calculation.py:142
                     ├─ 30.484 _construct_subdomain  lagtraj/forcings/profile_calculation.py:91
                     │  ├─ 19.276 interpolate_to_height_levels  lagtraj/domain/sources/__init__.py:31
                     │  │  └─ 19.183 interpolate_to_height_levels  lagtraj/domain/sources/era5/interpolation.py:9
                     │  │     ├─ 5.990 get_height_reversed_values  lagtraj/domain/sources/era5/interpolation.py:56
                     │  │     │  ├─ 5.353 values  xarray/core/dataarray.py:555
                     │  │     │  │     [430 frames hidden]  xarray, numpy, dask, queue, threading...
                     │  │     │  └─ 0.627 __getitem__  xarray/core/dataarray.py:626
                     │  │     │        [435 frames hidden]  xarray, dask, toolz, abc, _weakrefset...
                     │  │     ├─ 4.184 _compile_for_args  numba/core/dispatcher.py:337
                     │  │     │     [4953 frames hidden]  numba, llvmlite, abc, weakref, contex...
                     │  │     ├─ 4.028 calculate_heights_and_pressures  lagtraj/domain/sources/era5/utils.py:77
                     │  │     │  ├─ 1.116 _compile_for_args  numba/core/dispatcher.py:337
                     │  │     │  │     [2560 frames hidden]  numba, abc, _weakrefset, contextlib, ...
                     │  │     │  ├─ 1.088 values  xarray/core/dataarray.py:555
                     │  │     │  │     [274 frames hidden]  xarray, numpy, dask, queue, threading...
                     │  │     │  └─ 0.711 sel  xarray/core/dataset.py:1995
                     │  │     │        [366 frames hidden]  xarray, dask, toolz, abc, _weakrefset...
                     │  │     ├─ 1.225 steffen_3d  lagtraj/utils/interpolation.py:7
                     │  │     ├─ 0.843 __setitem__  xarray/core/dataset.py:1258
                     │  │     │     [484 frames hidden]  xarray, numpy, copy, pandas, _collect...
                     │  │     └─ 0.689 sel  xarray/core/dataset.py:1995
                     │  │           [371 frames hidden]  xarray, dask, toolz, abc, _weakrefset...
                     │  ├─ 8.151 sel  lagtraj/domain/sources/era5/load.py:146
                     │  │  ├─ 3.134 sel  xarray/core/dataarray.py:1027
                     │  │  │     [1081 frames hidden]  xarray, dask, toolz, abc, _weakrefset...
                     │  │  ├─ 1.852 __getitem__  xarray/core/dataarray.py:626
                     │  │  │     [186 frames hidden]  xarray, pandas, numpy, abc, _weakrefs...
                     │  │  ├─ 1.765 func  xarray/core/dataarray.py:2587
                     │  │  │     [378 frames hidden]  xarray, warnings, re, numpy, copy, ty...
                     │  │  └─ 1.187 merge  xarray/core/merge.py:577
                     │  │        [689 frames hidden]  xarray, dask, toolz, numpy, copy, pan...
                     │  └─ 2.081 where  xarray/core/common.py:1122
                     │        [1011 frames hidden]  xarray, dask, numpy, abc, _weakrefset...
                     ├─ 5.777 interp  xarray/core/dataarray.py:1304
                     │     [2446 frames hidden]  xarray, pandas, numpy, abc, _weakrefs...
                     ├─ 5.204 __setitem__  xarray/core/dataset.py:1258
                     │     [760 frames hidden]  xarray, _collections_abc, typing, num...
                     ├─ 3.806 compute_adv_profile  lagtraj/forcings/profile_calculation.py:50
                     │  └─ 3.429 calc_horizontal_gradients  lagtraj/utils/gradient_calculation.py:93
                     │     └─ 3.227 _era5_boundary_gradients  lagtraj/utils/gradient_calculation.py:45
                     │        ├─ 2.451 _compile_for_args  numba/core/dispatcher.py:337
                     │        │     [6122 frames hidden]  numba, enum, llvmlite, abc, inspect, ...
                     │        └─ 0.717 _boundary_gradients  lagtraj/utils/gradient_calculation.py:9
                     └─ 0.583 __getattr__  xarray/core/common.py:225
                           [220 frames hidden]  xarray, pandas, abc, _weakrefset, typ...
         2.975 _get_module_details  runpy.py:102
         ├─ 1.865 <module>  lagtraj/forcings/__init__.py:1
         │  └─ 1.450 <module>  lagtraj/forcings/utils/levels.py:4
         │     └─ 1.189 <module>  xarray/__init__.py:1
         │           [1784 frames hidden]  xarray, pandas, typing, textwrap, re,...
         └─ 1.107 <module>  lagtraj/__init__.py:1
            └─ 1.097 <module>  numba/__init__.py:3
                  [1508 frames hidden]  numba, llvmlite, pkg_resources, posix...
```

**Comment by sjboeing** [comment]
Really nice to have these plotting routines. Regarding the origin: check the following suggestion:
https://github.com/sjboeing/lagtraj/commit/d023d6a294299c0abacbad68e72f47dc06b0165d

(is there a better way to grep than:
grep u_traj *.py
grep u_traj */*.py
grep u_traj */*/*.py
?)

**Comment by leifdenby** [comment]
Thanks @sjboeing, that fixed it:

eurec4a_20191209_12_lag

I also tried it for a stationary trajectory, and it works:

eurec4a_20191209_12_eul

**Comment by leifdenby** [comment]
Also I usually just use 

`grep -r "u_start" .` 

or

`find . -iname "*.py" -exec grep "u_start" {} + `

if I can be bothered to type it out :)

**Pull request merged**
