### PR TITLE
Fix bug in converted forcings filepath

### PR DESCRIPTION
**Pull request by leifdenby**
Previously the lagtraj prefix (`lagtraj://`) was erroneously included in the filepath of the yaml-file defining how the conversion is done.

Closes https://github.com/EUREC4A-UK/lagtraj/issues/184

### CODE REVIEW

**Comment by leifdenby** [comment]
this is ready for review @sjboeing when you have a moment. Fixes #184 

```bash
$> python -m lagtraj.forcings.create lagtraj://eurec4a_20200202_first_short --conversion lagtraj://dephy
100%|█████████████████████████████████████████████████
Wrote forcing file to `/home/leifdenby/git-repos/lagtraj/data/forcings/eurec4a_20200202_first_short.nc`
Wrote converted forcing file to `/home/leifdenby/git-repos/lagtraj/data/forcings/eurec4a_20200202_first_short.dephy.nc`
$> tree data 
data
├── domains
│   ├── eurec4a_circle_data
│   │   ├── an_model_2020-02-02.nc
│   │   ├── an_single_2020-02-02.nc
│   │   ├── fc_model_2020-02-01.nc
│   │   ├── fc_model_2020-02-02.nc
│   │   ├── fc_single_2020-02-01.nc
│   │   ├── fc_single_2020-02-02.nc
│   │   └── VERSION
│   └── eurec4a_circle.yaml
├── forcings
│   ├── eurec4a_20200202_first_short.dephy.nc
│   ├── eurec4a_20200202_first_short.dephy.yaml
│   ├── eurec4a_20200202_first_short.nc
│   └── eurec4a_20200202_first_short.yaml
└── trajectories
    ├── eurec4a_20200202_first_short.nc
    └── eurec4a_20200202_first_short.yaml

4 directories, 14 files
```

**Review by sjboeing — COMMENTED** [review]
Thanks @leifdenby. May be quickest to go over this quickly tomorrow, it looks good but I need to get my head around the different subtypes, desc etc.

**Comment by leifdenby** [comment]
> Thanks @leifdenby. May be quickest to go over this quickly tomorrow, it looks good but I need to get my head around the different subtypes, desc etc.

The whole "types" and "subtypes" of input definitions is a bit hacky anyway. I should write a docstring for https://github.com/EUREC4A-UK/lagtraj/blob/655b41cf8c14a134261132b34618ba2448c041a4/lagtraj/input_definitions/load.py#L31 to explain what the difference is and what that function is doing. I'll do that and then it should be easier for you to review this.

**Comment by sjboeing** [comment]
@leifdenby: are you happy to merge this in, maybe we can add some more documentation later?

**Comment by leifdenby** [comment]
Tests are failing because python 3.6 is no longer supporting in Github actions CI. I'm trying to work around that in https://github.com/EUREC4A-UK/lagtraj/pull/186

I think we should talk about not supporting older python versions anyway. https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule

**Pull request merged**
